### ISSUE TITLE
GUI for aipman

### ISSUE THREAD

**Issue by Drsheppard01** [blueOkiris/aip-man#5]
I think a great idea would be to make a gui and integrate appstream-rs so that when you click on a link like appstream:// it opens the GUI for aipman and you can install it immediately. This way aipman would combine both appimage and appcenter functionality and potentially eliminate the traditional .deb or .rpm packages 

I think I found something similar but for flatpak https://github.com/ItsJamie9494/catalogue

**Comment by blueOkiris** [comment]
I do have a frontend for aip-man already, in the form of [aipster](https://github.com/blueOkiris/aipster). It's kinda clunky, but perhaps it could be reworked to be smoother and add that functionality.

**Comment by Drsheppard01** [comment]
Oh, thank you. Maybe @relm4 can help you make it cooler
